apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-store
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    gcpsm:
      projectID: project-f7af048a-a298-4d12-b7e
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pawmap-secrets-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: pawmap-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: MAIL_PASS
      remoteRef:
        key: MAIL_PASS
    - secretKey: MERCADO_PAGO_ACCESS_TOKEN
      remoteRef:
        key: MERCADO_PAGO_ACCESS_TOKEN
